"use client";
import type { Metadata } from "next";
import { createContext, useContext } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Theme = {
  colors: {
    primary: string;
    secondary: string;
  };
};

const defaultTheme: Theme = {
  colors: {
    primary: "#007bff",
    secondary: "#6c757d",
  },
};

export const ThemeContext = createContext<Theme>(defaultTheme);

export const ThemeProvider = ({ children }: { children: React.ReactNode }) => (
  <ThemeContext value={defaultTheme}>{children}</ThemeContext>
);

export const useTheme = () => useContext(ThemeContext);
